### ISSUE TITLE
getrandom() clears all flags

### ISSUE THREAD

**Issue by haraldh** [enarx/sallyport#116]
https://github.com/enarx/sallyport/blob/d28863940e463ee32cb1e29d400db2d2300e3264/src/guest/call/syscall/stub.rs#L129-L132

It think it is meant to be:
```rust
        if flags & !(libc::GRND_NONBLOCK | libc::GRND_RANDOM) != 0 {
            return Err(EINVAL);
        }
```
because otherwise checking for the flags later in the code does not make sense if `flags == 0` anyway.

**Comment by rvolosatovs** [comment]
The intention is clearly to check whether `GRND_NONBLOCK` or `GRND_RANDOM` (and only those) are set

**Comment by haraldh** [comment]
ah, later on `self.flags` is used and not `flags` like in the original code. so, all good

**Comment by rvolosatovs** [comment]
Probably still good to get rid of `flags` variable to avoid confusion

**Comment by haraldh** [comment]
true... opened a PR
