### ISSUE TITLE
[Feature]: `type Ref = NonNull<c_void>;`

### ISSUE THREAD

**Issue by jarkkojs** [enarx/sallyport#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since `NonNull<c_void>` is used so heavily across the board, I think there should be a type for that. E.g. I use `Ref` in the https://crates.io/crates/mmledger for that. It's a cosmetic feature but sure makes the code more pleasant for the eye.

I prefer`Ref` over `Pointer` because it is very compact, which means that it does not get in the way of other more relevant information in the source code. Normally I try to avoid abbreviations, but in `Ref`'s case I think it is less cluttered looking than as a full-blown word, and we can probably say that it is quite universal among the programmers of types and sorts.

**Comment by jarkkojs** [comment]
Sorry guys. I do not know to who SallyPort should be assigned.

**Comment by jarkkojs** [comment]
Here's a bash script that implements the change written out of top of my head but should be almost there at least:

```bash
#!/usr/bin/env bash
OLD='NonVoid<c_void>'
git grep -l "$OLD" | xargs sed -i "s/$OLD/Ref/g"
```

**Comment by rvolosatovs** [comment]
I don't think this belongs in `sallyport`, why don't you define this type alias where it is used?

**Comment by jarkkojs** [comment]
You can do as you like and sure I can alias it. It just makes IMHO things a lot cleaner:
```rust
   fn mmap(
        &mut self,
        platform: &impl Platform,
        addr: Option<Ref>,
        length: size_t,
        prot: c_int,
        flags: c_int,
        fd: c_int,
        offset: off_t,
    ) -> Result<Ref>;
```
Most blocks in our Enarx ecosystem make a typeless reference like this so wouldn't it make sense to "standardize" it so that you cannot get it wrong? You know exactly what to pick for a Rust's `std::any`.

**Comment by jarkkojs** [comment]
The name is not the sticking point for me but having some common type is what I'm going here for.

**Comment by rvolosatovs** [comment]
As a general rule we try to avoid adding type aliases like this, which do not provide any additional functionality.
This would be one additional layer of abstraction the consumer of the API would need to be aware of and we don't want that unless there is a substantial reason to do so. This cosmetic change would make the signature look "nicer", but it would make the API harder to use, by increasing complexity.

**Comment by jarkkojs** [comment]
OK :-) I think differently than when I put this anyway but thank you for confirmation, I agree :-)
