### ISSUE TITLE
[Feature]:  get rid of core_ffi_c

### ISSUE THREAD

**Issue by jarkkojs** [enarx/sallyport#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

```
mustikka in sallyport on  feat/enarxcall/reset-sgx-permissions [?] is 📦 v0.3.0 
$ git grep "[^a-z_]c_[a-z_]*" | sed 's/.*\(c_[a-z]*\).*/\1/g' | sort | uniq
c_char
c_int
c_long
c_path
c_short
c_size
c_uint
c_ulong
c_void
```

Refactor:

* `c_char` -> `u8`
* `c_int` -> `isize`
* `c_long` -> `isize`
* `c_size` -> `usize`
* `c_short` -> `i16` 
* `c_long` -> `isize`
* `c_uint` -> `isize` 
* `c_ulong` -> `usize`
* `c_void` (page-aligned) -> `primordial::Address<usize, primordial::Page>`
* `c_void` (unaligned) -> `primordial::Address<usize, ()>`

**Comment by haraldh** [comment]
no

**Comment by jarkkojs** [comment]
you probably know better
