### ISSUE TITLE
[Feature]: SGX2 enarxcalls

### ISSUE THREAD

**Issue by jarkkojs** [enarx/sallyport#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. `TrimSgxPages(addr, length)`
2. `RemoveSgxPages(addr, length)`
3. `ResetSgxPermissions(addr, length)`

**SEQUENCES**

`mprotect()` guest handler:

1. Update heap.
2. `ResetSgxPermissions()`
3. `self.accept_mprotect()`

`munmap()` guest handler:

1. Update heap.
2. `TrimSgxPages()`
3. `self.accept_munmap()`
4. `RemoveSgxPages()`

More information:

https://github.com/enarx/enarx/issues/1531

**Comment by jarkkojs** [comment]
@rvolosatovs these will also need probably that fallible passthrough.

**Comment by jarkkojs** [comment]
Because there are so many, should the calls be prefixed with `Sgx` instead, and perhaps also existing ones?

**Comment by rvolosatovs** [comment]
> Because there are so many, should the calls be prefixed with `Sgx` instead, and perhaps also existing ones?

I think it's fine as-is, but it probably does not matter much. What do we get by using the prefix?

**Comment by platten** [comment]
To be scheduled for the 0.5 release.

**Comment by jarkkojs** [comment]
> > Because there are so many, should the calls be prefixed with `Sgx` instead, and perhaps also existing ones?
> 
> I think it's fine as-is, but it probably does not matter much. What do we gain by using the prefix?
 
Prefixes are a bit easier to grep from logs.
