### ISSUE TITLE
Syscall feature-parity

### ISSUE THREAD

**Issue by rvolosatovs** [enarx/sallyport#34]
v0.2 version of the crate should implement all syscalls implemented by v0.1

Follow-up for #17 
Requires #68 
Requires #78 

### Still unimplemented

Common syscalls:
- [x] #56 
- [x] #57 
- [x] #58 
- [x] https://github.com/enarx/sallyport/pull/62
- [x] #63 
- [x] #64 
- [x] #66 
- [x] #67 
- [x] #47 
- [x] #72 
- [x] #65 
- [x] #75 
- [x] #76 
- [x] #77 
- [x] #49 (#60)
- [x] #79  (#59)

Enarx-specific calls:
- [x] #81 
- [x] get_attestation (blocked by implementation of the call in 0.1, issue ref TBA)

**Comment by bstrie** [comment]
Can this be closed now?
